version: '2'

services:
  php:
    build:
      context: ./docker
    container_name: "php"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
  mysql:
    image: mysql:5.7
    container_name: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .data/mysql:/var/lib/mysql/
